language: php
php:
  - 7.1
  - 7.3
  - 7.4
install: composer install
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
before_script:
      - export XDEBUG_MODE=coverage
after_script:
  - bash <(curl -s https://codecov.io/bash)
